version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: farmacia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: farmacia
      MYSQL_USER: farmacia_user
      MYSQL_PASSWORD: farmacia_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: farmacia-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
